stages:
  - lint
  - test
  - build
  - deploy


lint:
  stage: lint
  script:
    - echo "Running lint tests"
    # Add your linting commands here

test:
  stage: test
  script:
    - echo "Running unit tests"
    # Add your unit testing commands here

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t 192.168.1.202:5000/test:dev .
    - docker push 192.168.1.202:5000/test:dev

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes"
    # Add your Kubernetes deployment commands here
    # For example, you can use kubectl apply -f your_deployment.yaml
